### ISSUE TITLE
Source resolver stops reconciling

### ISSUE THREAD

**Issue by tomkennedy513** [buildpacks-community/kpack#1127]
Occasionally the sourceresolver reconciler stops reconciling, preventing images from creating new builds. The current workaround is to restart the kpack controller, but we should add a timeout for source resolution to prevent issues where one reconcile that is hanging can cause all other images to wait

note: this may be do to a blocking call to libgit2 that never finishes

**Comment by samj1912** [comment]
Is this fixed now given the migration to go git?

**Comment by tomkennedy513** [comment]
We're pretty confident that it is, but we have only been running the latest release in production for a few weeks so we hadn't closed it yet. I think it's probably fine to close this now
