### ISSUE TITLE
Sign an image using Cosign with the SHA256 digest

### ISSUE THREAD

**Issue by gl172** [buildpacks-community/kpack#1265]
Is it possible to sign the SHA256 digest of an image rather than the tag? I've got the kubernetes secret configured and attached and the image gets signed however I get the attached message suggesting I should use a digest. This is during the image create/save/patch process using kp. I can’t find any doco to say if it’s possible and how. 
![IMG_8208](https://github.com/buildpacks-community/kpack/assets/19371888/e067ad33-e742-4193-8144-ec60315e4665)

**Comment by tomkennedy513** [comment]
I would be favor of doing this sooner rather than later

**Comment by gl172** [comment]
Especially since you get the message that signing tags will be removed soon.

**Comment by tomkennedy513** [comment]
@gl172 What version of kpack are you using?

**Comment by gl172** [comment]
kpack and kp-cli are both 0.10.0
I'm using these as part of Tanzu Build Service
