### ISSUE TITLE
Edit  image don't trigger new build

### ISSUE THREAD

**Issue by smile37773** [buildpacks-community/kpack#1356]
![image](https://github.com/buildpacks-community/kpack/assets/34502364/7311d4aa-0cf1-44b6-a77f-f4918c72926d)
We edit the image but don't trigger a new build.
As the above picture shows, the image generation is 41 but the latestBuildImageGeneration is 28. 
I want to know why not trigger new build?

**Comment by tomkennedy513** [comment]
What fields are you changing on the image

**Comment by smile37773** [comment]
I changed the blob url.

**Comment by smile37773** [comment]
@tomkennedy513  I found create new image also don't trigger build.

**Comment by tomkennedy513** [comment]
Are build resources being created? Can you get the kpack controller logs

**Comment by tomkennedy513** [comment]
Also, what version of kpack is this?

**Comment by smile37773** [comment]
@tomkennedy513  The kpack version is 0.11.2.
There is no build resource being created. Creating Builder also isn't reconciled.
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB2YAAAA5CAYAAADtPEvDAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAB9pSURBVHhe7d0LnE514sfx7zBlzHZD7kvoIsSaDNnINVK0tkKSNFIoNG4llxXFGMolGhHtyNZKqm2p0NK45H6/jiR/DHIfYcxMnu38z3nOmZlnZp6Z5wwz2t0+79fryzm/8zuX3+885+j1/DrPCZJkmAkgWuuTB6lu0jZFTf/SKfORsl9DX3/PmamrJ/tP08TRt6iQftHBof3Uc8KH2uAsjd6YrEE1dmhM0Xoa4pRl5mZft7uo01DxRoTKLOurYk3fchaYIuOUOKmJjs0KUrWubvblZjtOmRux8TIiymhZ32Ly3ZzXvZ/r8Kq2KhE/VY2q90rvs9zExhuKKLNMfYs1VdbNpfFfx905jYxL1KQmxzQrqJoymhnrp0/8lV2uSMUlTlKTY7MUlEvn+m1XpvPibEdOHW/f36mgoLGB236uc47n1+6TJHM7v7+K/cM1mPt2nLJc2efgd/+op8f0qRbe8Jq+vXOK7vhnIz1d9lOtf/CEgoqG5+Gc2gr6GnSj7pP99epro1X/wgRN/8IpVBv1GFJLhb3HXNtV2wNvJy9td/+Zz2k7rs5F1HolD64r7f9Sr7+32lx+r7q9dJd+mDBKI16fKavEjcD7KuvqfLk9F7l/nl1+Npx72p6A18C9evYvrVU5xJys+6T6tyito18O1fCRE/Shv39ocvt3CgAAAAAAAADgisfjcaYyswZmA+Q+49PDhmEc+sSo53d5RsI7zTN+SE42Ds7vZ/Rbd8owkn8w5nUKT1/e4HNrQyeMxa2zr2vHzb7c1Ik2Niabu18flam89awfDLPYiI+15vNrO3lI9EZzvWRjfZSfZWpnLDW7zEjebcSE+1uePbHxZv3EOCPSz7K0+K/j7pxGxiVarTRiM5XHmiXWJiN9yvz3U7aEdzL6DR5sDB7c3Wjtb7k3kYa921g/yzLit12RcYa9qjXvbCetjncFwyx30fYG0409ZntOLG6dZVm4EbPbXHBqqXfeb/+0Xmx+wi+zf3KMu/NlhWswp9jbSYyLMs9horExWkY784JL3h1jRFnn8fDn3nruP/N2CvoaDBznM5l80Ph7O99y32N203Y32/EtD9R295/5nLYT+FyEG51WmVfbqe1GVFRURoY/ZzTItE7gBN6Xm/Pl/lxc+XVhxrmn5enfoQbPGcP/dTCXf4fMe8hnh8ytHjY+b+B/OSGEEEIIIYQQQgghhJDA8Xg82VLIXODCSn248qBSStbWq90fcsr8aN1dr77eRuVO/Eujxk7UxDdGa0dSFbV5fZA6hdtVVn2wQodSSipsZL/0Mi9z3e6trQk3+3JTZ4E2HUxRSKXG6fsJ79RPI5uVs2e88ms7ebBgkw6mhKhSHW9js/hE74zeodMhldXq1Sz9o9bqbndQPnF5Tl1boMOnlamf/AnvOkxRUVFmRunF/GxOnrho+6rZGr/9tEqGjXQ+l7bwToPUqrJ06Ot3vPMbf0oy/yyhcml1zM/x4JFhKunMZnDXPzlzeb64BnPhnIOKLdWq7HFtWmBece9sU1LlVmpZMUQpx/Y49a4Wl+c0oCIqf4P1KGSSEg/YJWYHqd/gmuYnM42btrvZTl5c6WfejSLqcIt5tV3cp8+GDNGQtLw2Q6ucGvnHzflydy7y57pwybyu+/megFUz9NVe674lFfL7XwDh6nqn2acpx7Qn/zsRAAAAAAAAAH7TCpsZYU/mLv74BQWfCdOjA+9TocIl1LBhw/TcecO32nxjJ/UdP04v1vBo80u99fznCdLutTrpeUwPdKyve8smafKctWbZMSUFn1CNB4bogSr/VugtznY6/kmFt8/Wmt0u9vW9mzoJSkwNVt0W7dL307lre62de1y3Nymvn7eOVMw/8287riUkquZTndSoShltfOMDmU3JZPfak/KEHFKNtln6p2FH/anwds02Oyi8U191ad3EW960+f0qF/qLLv07VLeY8+EVU7R2x1FXddz0c/2IV9Sq0gVtHRmjjGb+Wb1H1NZ1BxZp7PvrnLIEedRQ9R+spyYVMo47bV9pKrftoy51blawUnTwH+M02zzf2dVXxCutVOnCVo3M0rkB2/W7lnqlVSVd8J4XZzs6oEVj39e6P/fWiNo3a+TIka7O++azHoXUeVgDGxVS4eL2ss4DH9Pv3pusNz98R5vNj3iCR2pY/0HVrvdvu06vnur0r++VGl5FRQ7nvX9yE/CYuQYDSFDtTq+oSY2KKnrwMw0Y9IUSdl/UA/16qEH5YB3f8IomfJTg6jN/Na/BwJzPVvNaqpL22ercVe3PFVGJhqVVyHvM81y0fZWL7bhre6bjyuEz72Y7gc/FPHMfj6l5mwqq4qyb1n9Wqt3otg/d3evcfFbdnIv8uS6sw7Pvaadyuwb+0FhDe3bULWVvTV+/8+P36ZfpkzX1i+Xe+1gm4UP0Rr97VWjHCI2cudk8iwAAAAAAAACAyzF8+HBnKoPrgVkd2qzlS0/KUzxVxUNCFOKTf59aqjXJ9fVA8AGt/XaxPhn3sdLG23avsQcaD5wM1tKly82SBG1evlQnPdcpMclnO9vna9R7zlqB9mVVc1EnYfPyTPs5uf4TDY5eLYXs9x5Dvm7HNWuQ6U9q27Gawo7u1rvZRg12a81SP/0Tsl3zR73n7dfK9R9QrbLXecv3b/lW367bpZNOveCk/Vq+OcFVHTdtD742RCd2rTHrrUk/p9I1KmK2fcuKZfZ2HLvX7FdScKKOJmZsJ31fjoTEVAWf2OX9nMyf4rtNX8G6NuSEdq1ZrqVZOjdgu7YdU4i5/TXe8+JsZ+0KLVu+WQnXFDFP2Rbzc7jU3Wds9xotPelR8eTi6ctO7lqqjwZH64O0Jpl19icFKynRPqaQ/SvN5R9qQ7C539V5759cBTpmrsGAko1g8/O8Vsu+mqe/eft9ty567M/S0sWx3u24+cxfzWvQjWyfrZPr9cng+druc8xu2u5mO67a5cjtM+9mO4HPRS01aNxIzZpcr9Nbv9cZZ30rj/UZobZhP+mNd9c66+XO1b3Oxfly04f5dV3IuaetzO0aMO9Rh66tnt7X3v1lvY/5aB01Rd3vOq8vBz6lSTltEwAAAAAAAAAQkL+B2SAz1u8c46pqrzkH/6aORXfquYhwzfzKKQYAuBf+mQ5teESl9s5Q86rdM/188diNKXq5TrKCgoo5JQjooWe1cdYMVTrQQ23rvVsAPwcNAAAAAAAAAL8dHo/Hmcrg8h2zyF/z9PboaO0oVEdRr0XqiQJ7/yIA/A8rUsj7j9gvnp+VapfYwp9Q5WK/SKknnAIEZPZZ5GtRuit5qca8waAsAAAAAAAAABQE9z9ljHyVsGmZTv/SSE07Rqj+L4s09asfnSUAAFcSflGh0Gqq/0A1Vb4UoooNGqiBlc4v6elyOzU5ZqaWLNvkVEZuHhz9ud6tf1bjRrykqNmHnFIAAAAAAAAAwOXip4z/4zRUj5EPq9zRBXp1+rdOGQDAvQ4aOLaOSjpzaVL2c1/Niw4Dx6qONmnQmx87JQAAAAAAAACAK+Hvp4wZmAUAAAAAAAAAAACAfMQ7ZgEAAAAAAAAAAADgV8DALAAAAAAAAAAAAAAUMAZmAQAAAAAAAAAAAKCAMTALAAAAAAAAAAAAAAWMgVkAAAAAAAAAAAAAKGAMzAIAAAAAAAAAAABAAQsyY9iTuXlAEf1rqLg5dWbXBM1abJdaHojorxqhCZowdZ5TYnogQv1rWLVTlBA3VfO22MUZ2zmjXRNmKX0zYe31QtMKCjHLJ5jlGetnl3X/AHw519iZXZoQ6ELJ6TrN5fqzpZjX6VT312n69Z3GZ38u9xXW/gU1rZCxBV/2vlzeW9Lk1HYf2ffps223bQcAAAAAAAAAAK7Uaf+CGmcbC0jRoWVT9clmZzYv38/nOBaQMe6ZSUqC4qbOk1Wt/Qv9VSEky5hDGmfsYeqECU6Bfx6Px5nK4HJgNlbxRoTuTE1Vwoan1PY++6C8S+INRZRZpqBiTZ0SszmLjmtRXbPu727WuRkNdFef9Nr2dnRCi1uVViunJWFTdmpV7xoqqj0KCqpmbVRGxJ1+BzhObBigsR85MwCycK6xPbMUVK2rU+Zfjtdpx0EaX7eUPa271b5XE1VI8h3oTdGAAUPdXafWTa/nUP2lzmH9dV7aXbOa7i7/saI7mjczl/tq9MJotb3Vuhlnr2Pvy+W9xZHzPcpi35DbPv8X1Tn8V6UftsJU44d31Mr6n1C4RwEAAAAAAAAAkK8GfJOoN5v+op0TZulrb0m42veqq5RFAzXkNWdwNg/fzwcar6ycsEwx6YMAd6v9M7/Xptcn6u9xU1Vy9CFNeLCItnftonqZdhSm9h99rPcfL67QoBJOmX/+BmYt1sBsgMQa8Ybp8F5jb+JOY3JYxrJYa0FinE/dlsai44Zx+ptexsy9KcbFnZONsLRlYZ8ah4wUIyHhtHF8UUunfpgxeWeit8ww9+It827UnIt11iOEuIxzrcbH+lnmm1yu00yJNOISc9hewOs0zGi3wtxJSoLxVa9GPuWNjF6jXzGeyFTXSi77Sk8OddzeW7zJve0tn15nHDdOG7smjDZ6Ncool54wXhndy57mHkUIIYQQQgghhBBCCCGE5GsGfGMNAOw2ZqaXNTFe2GB9x3/R2DGljl3m+vv53MYC7LGUxLhIn/rW2MUu47S5r+/ntDPUqJfxVUKKYRxfYbTzGRdVy/eM7y+a2931is+6/uPxeLIlb++YPR+vFSfL68HeLZ0CP1r2V1ipM9o2I0azVxxSoSrN1NVsqVej4rpeydq3eJuCw4bJbIhZv7cevOkHRS/+P6Xqd3Y9AAUrt+s03zRSr5qlpF9+1OaYFU6ZZYVihkZrjjOXL/Jyb8mt7WHtNGxcPd14eIlG9R+qTIdtHnH00BhnGgAAAAAAAAAAFKxlmrrjuPl3URWrcL1d5Faex0GssYtRWnK4kG5rO8KcjVF09E6dKRWuMS+3k71qmNoNa6PbCh3WklHR3pK8ytvArM5o9ls/qHjrfsppaLZlv9oqdWabZswxj3l2vE4VraJmWVu6Y4a2BYdrhFnesl9rFd87XjE7zitZeexUAJfF1XV6xbbokx/OmPfLimrRt6/6dsnlf+jILy7uLbm2/bGXFF5KOrU5Jn8HjgEAAAAAAAAAQB7dry7VrTfBntF3c5fZRS5d3jjIHK3elyyZdS0rYsbrzd3Juq3tGPVqaT3b9bLGhN+ow3HRirnMQYQ8DszaB7HkUnUN8z6SllVL9QsrrTPbZtiDGis+0t4zRVWlWVd7JLlkqIooSee2zNGMJadVvtnLGhZ2jbZZveJHsep91dca0EnP8/aTcACuQIDrNI9yvk5XKGb8m5o0aY/KRU/UxHGvO8u75Pg/dlw21/eW3NseVq2Mipp/nz+T9qhsS3Xxbdvz7ZxyG/coAAAAAAAAAADyU3HVSP/O/XWNu/2UJk16wzvA6iv37+cvfxxky7kk809rpMAyR2NGLdHhQrepzbDn9fKYtqpwOk7RY2KU6Qc38yDPA7PWQUxdnKqaY3qphVOSrkU/hZVO1YGNab0zRzO3J6polQfVy6pc/gazKedljXnMmbpYJ8u3Vc1LSzUzvTOLOH/brr2ukipV8k1FlbnBWQjg8gS6TvMo1+t0zhj16/eqxk58S299tEaVnhuuiRPH6fXISD11GfvKkdt7S4C23xAc7JSnuVm/d9r13PCJmhjVyym3cY8CAAAAAAAAACA/XaPrvd+3P6r+0fVV+tIprZwdrY+cpWly/X7+CsZBznn+7Uw55kzV2LjDuil8vNrelqKdY6OzvAYx7/y+kDZz7JfgGvGx9nzj3sbGM8eMhS1keN+xmxjnLW+x8Jg5c9H4/tNIIzLSyTqrzDCOLWzhvJA33oj1brOx0XvMJGNM78b2NiPjDOuVvt5p1y/uJYRkTpZr1U8CXqeZ6kcacdaF6W97l3OddhpiTJq0yzhj7WvFY1mW57Kv9ORQx+W9JWDbx20yUszpg5/Wzti2E997HfcoQgghhBBCCCGEEEIIISR/M+Ab69v83cZM73xTo9eiQ0aKcdHY+979GfVcfD8feBzEHktJjIvMtu6odRfNJWcylzeeaey1Bg/OxBmdfMsDxOPxZMtlPDFrWv62Jm67VmH973cKLPerf1hppR7eoK8OV1GVKk7WzlV8olQ6rL9q3xDq1LUs19uD+2rw28udeQAFL/B1WqD+HqW+fdfLelV36Zq97bJ84O7e4qLtX27VoVSpZNWuqu2sBQAAAAAAAAAArrY4xUSP047Eorq99TA94vo1glcwDlL7Ud13S1EpcZtT4Fi+Q0eSzb+PH9Df7ZIr4ncUN3P8PIX35MdGwsHlxvKD3iFlQ/cvNI4ZKcbe95yn1HzyZJz3+Tgj0n7UzXmqLUsa/9M4Yi71TvM0GiGXmQBPzLq4TjOXX8kTs/cbnXs8atTOUl770eXmXgzjzKY+mcqv5IlZV/cWV21vbPRZlGCkXNxrfJrl2HlilhBCCCGEEEIIIYQQQggpuGR+YtbOE/MSvE/Nfvdec7ss0PfzrsYC/DwxW/tRo8ene809nTF2D30yo9wbN+MX2ZN/T8xaPpyqr3+upbol7dn7B4SpdGqCVv4t+xOwH87cpkSVduZysPyMzjmTaYpV66M+fTKns+9DugD8K1Yt27XTx7x4rvg69SPn67S0bnmkj17KsmxY9G06M2WKxk+Y4l3fjT880t1Z/z6Vt14X69O+gPcE597iru3LNSX6Db0185juiY7WMGcfVqoVk1JP7bdXcHCPAgAAAAAAAACg4MyZOk47E4vqjtbDnBJbTt/P52UcpEj5+zLWHxat4dUWaeaU8Ro9+kOnRv4rbGaEPZmb63RTiSPatWalFq7c4ZQd0Lmg4ko+sFnr163W2e9/1JGtizR35jpzSRY7PAo219+wep3O79uglQtXKm0rGex9rFy40Jy8SSWO7NKuIyVUokTmBJ9dqPRDAJCFc63uOpLt2ikRfFZnD/0U8Dr1XoPpiurG4ue1b4Pvte8IeJ3u0MrDN+qehrertM+y8/uWac6LQxST7TrOeV/VWnZQw9tLm+ubyzev13qf9ln72nCweMB7iyd+l7u2H1inJQv/T57i1+ia0hnHfWTXen27aK6WrDPX5h4FAAAAAAAAAEC+KnpDcZ3btzHzd/0H1utCcAkdPXhQCxcuCfj9vOdcRRdjASu94wZ7953PWP/8Pi2b86KGjPM3zpDLWEkuhg8f7kxlCDJjPU4LAAAAAAAAAAAAAMgHHo/Hmcpw+T9lDAAAAAAAAAAAAABwhYFZAAAAAAAAAAAAAChgDMwCAAAAAAAAAAAAQAFjYBYAAAAAAAAAAAAAChgDswAAAAAAAAAAAABQwBiYBQAAAAAAAAAAAIACxsAsAAAAAAAAAAAAABQwBmYBAAAAAAAAAAAAoIAFmTHsyctQ80/q2qCcLn43TXPjnLK8cNYv4sxKqZo2LdaZzgdZt596VKti52uHM1vg6J8cNX28p6oWs3a5SrHzr9oZAQAAAAAAAAAAAAqcx+NxpjJc2cBsZJwSJzXRsVlBqtbVKXPLGhQc9obebmlo9kdpo5bJev75/s50PmjWTxPa36Gi5mTTjj1VVcvUt1hTvWUv9dFUj/esqtD8HiSkf3IUG28o4k7p7LK+KtY0+x4BAAAAAAAAAACA/1b+BmYt1sDs5SUyzkg0DCM+1s+yAKk5cbuRZKQaRz592u/y/E5svHmgiXFGpJ9lUqxhL470s+wKQv/kmKdHTDOmTZtmTOzfzO/y/7rUfNiI6NHD6NEjwni4pp/lhBBCCCGEEEIIIYQQQggh5DcTj8eTLb/aO2ab1a6gUJ3Sppj3nRL4+l/vn/dH9FTPnj3Vb8I3Tsl/q5p6OKKHerzUX5HDJ2vatInq38xZBAAAAAAAAAAAADjy+FPGTfR4j6q6yZlTs/6a0OEOHcr0U7211Cbijyqf8eJSHVk9S19k+QXcyLhETWpyTLOCqsnvr/zWfFgR92Z+v+pRczsLnO3UfDhC95ZL1nfT52qZXWSyj6/o0dWalVbR4f3p3DKZf6rX3oa1h6c1YtofdcPej9XfZ6Aw1c92ckf/5CRjW5md/W665mYcYO7t8i4rodOrDyj0Xquf7WXnq/dQVavTU49q+iYFrnMgVD3MGX/H3+Rxq95ZTTf7zY0mj8/V5NG/1+oFn+pC7b9oQBNpWd9i4teZAQAAAAAAAAAAfrs8V/SO2bva6Ol7B+u1V4O0KG0UsWYbRfyxnPanDzw2Uvvufcw6NbXii+XeKrXadNBNq/pq4Ovv68viHdTdOzpmjVlO1ONVz2l1j1eV/kzo2e/07sfWeo3VYfYIdU/eqx/sJWrSobOMxS9o4Kj39cXOnAYuYxVvRKiMn/eW+ht4bD5gkjrcYb1htYk6dL9DoUfXaJbPCGny3o/Vd/xSZy4A+idXGdtyZOsbS4B2Nbfe2VtbCX/bqku3FVGZOn/Q6bkv6HzdIdpZqJS6/z5BQUNOB67Ta5+OTH9EN303SffU6iezuxyN9eWPy/RQyAoFFWvslOUuYuR01T5n94Pd5wzMAgAAAAAAAAAA/Nb5G5i1ZPq945zSeNoeIyn1iLFkQPOM8izvUK3VZqlx1CzZM7JLep0W/b8xjqQmGfHvNjIUMdKYPn26N6uPpFpvLTW+c+a9GRnhrBdhjJw0wGjubMNKxGdHjFQjydg+8S7vfGScd89GrE8d5fIu1IJ+hyr9k8f4ff9ugHZ510kyko5sMQY0jzSsJiYlHTG+s/rF24Akd3XU3IjdZ/Zv0nZj4l0++2/8pfGj9V7fz9L6OW+x+zzRiIv0v5wQQgghhBBCCCGEEEIIIYT8NuL7btm0mOX+K2dOY+PLHw0jdV9spkGzzINrNY1J25K8g3tdfOuopfH5UbPSgbk+ZTkNHOaS5vMNazNpg4P/WQOP9E+e43dg1k982+Wsk7jcGji1B12N1M3Gm1Y9bwMMd3XM6eax+zINZFtpbJ9EI7a5s+88hoFZQgghhBBCCCGEEEIIIYQQYsXfwGwhc4ELEapSRrqYsFU5/3BtB91zW6iUEqwizz2n59Jzi0pYP5h84812NZfuat3FZxtmqpTw/u7yfyb6p3F7n2Nx0qX1Xc5S99y069j+Wc6U6eJPSnAmfQWqs/SDadp9NlS3Nu8m+ygb6+W7y+js7mn6wOWvVwMAAAAAAAAAAABuuRyYdaOorgk2/wopqXr16mXKni9maubfvrKruVCj9VMaOv4djRvou52bFeIs/+/0v90/VWr5Houd8GplnKXuXNV2LX1Tk7efVeitzfVMDXO+0cu6u8xZbZ/8Zi6D6wAAAAAAAAAAAMDlcTkwe1rJP0vXFi3hzNsaVSura51p6WsdPm3+9dM2TfZ94jEtL463qwVUQ93GTFPHyj8pLtp3G6t1zKmRo0aldJMzmTf+25dNjdZ66tln9eyz7dTIKbLRP7F/8T0WOy++ucRZ6sYVtOsyxc6K04/Bt+r+bjXUaNDdKnN2u2bFOgt95XjeAQAAAAAAAAAAAHdcDswu0vaEnxVasaEesp4uNNV4qLOiWlWW9RCo7Wt9vv6ofi5ZS8Mea+iUXY6yuv3mUMlzSgfWO0U1HlLnbrfrRmfWsutCsvnnjSp1nz2v+x5Tt6gw5e0ZzTSLdOS0MrXPnxrdxmjajBmaMWOyBqXt14v+uXLu2pWvYqfq64Rg3frQMEWFFdePy96X33HZHM87AAAAAAAAAAAA4I7Lgdkl+mD6u/o+9B5NGNZN3bp107DhA7VnQbysh0DTzIqZqHfnFFLLKVHeOr55zPWA1hL9469rvU8yPuTsq9uw4Rr4x1IKdWpYlvzjr1r7YwmFjXHqjBmlQXsO6sefnQoma3A0bf+3W6N715ZVfWe+c6YRRmefJTLal72OVLZ4qDPQGqrrbvdOOOifK+euXfnLPG/fJii4akc1KJGgr2P+6pRnlvN5z9yH9ctaz0dfq7L1nePv/JBdCQAAAAAAAAAAAL95hc2MsCdzt3/1QiVdf6tUpIIqVKigSzs+0bMD16l4xdOK/3a+vtniraSF8y/o+urXqbpZx6qXluuSnDqOG0qb20jYqm/nfyOfYq8t3xxS4TLSRTnrX9qhT55doH3mvvaujdNXq/ZblXTIrBSiKnad0xs059lYbS9zSYc22XVqP9JdD4bZy0/v26ItOxN0yTmeMoUP2ttxZNunnzr7k0JU5lKCdm6J04KRmY+b/smj+hF6pVUlXdg6UjH/tIsCtmvHBbMsQVu9/XmDSle4pIQdaxX31SrtL1FOFU9/r/lxawPXmT/f3qFp/y2PaIB5HIUOLtDgvp/LX2tyO+++fXgpYae2bNmphEvO8ZcprPnmfgEAAAAAAAAAAPDbMnz4cGcqQ5AZw54Erp7qE7ZpQ7879d2EIrp7gFP4K7CP4xZ9P6i9ao/7l1MKAAAAAAAAAAAAXD6Px+NMZXD5U8bAlaiuVo+0Mv9M01C9H7xNoT/t0dxFTtGvoeEjGmYex6V9UzWFQVkAAAAAAAAAAAAUIJ6YxVXQQoM+H6I7/zlbK7zzz2j0xDJaNDVazwx5z1tyNVVv9aTusd4H+8xoTSyzSFOjn9GvcBgAAAAAAAAAAAD4H+XviVkGZnF1tBikt5+oqlBnVsdW/SqDspYWg97WE1XtIzm2ikFZAAAAAAAAAAAA5C8GZgEAAAAAAAAAAACggPGOWQAAAAAAAAAAAAC46qT/ByXh4ripjAGoAAAAAElFTkSuQmCC" alt="image" iscopyblocked="false">

**Comment by tomkennedy513** [comment]
Can you get logs from the kpack controller (in the kpack namespace)

**Comment by smile37773** [comment]
@tomkennedy513  There are no errors in kpack controller logs. Then we reinstalled the kpack, and we found this error in kpack controller.
```
2023/10/19 02:57:53 Error reading/parsing logging configuration: timed out waiting for the condition: Get "[https://10.0.0.1:443/api/v1/namespaces/kpack/configmaps/config-logging":](https://10.0.0.1/api/v1/namespaces/kpack/configmaps/config-logging%22:) read tcp 10.1.5.163:47886->10.0.0.1:443: read: connection reset by peer - error from a previous attempt: read tcp 10.1.5.163:47874->10.0.0.1:443: read: connection reset by peer
```
