### ISSUE TITLE
How to create image on air-gapped cluster

### ISSUE THREAD

**Issue by rbuffi** [buildpacks-community/kpack#1660]
Hello,

We are trying to build our python images on an air-gapped environment.
We have taken the following steps:

- Load images in harbor registry
- Inject custom cert with webhook

During image build phase "build" the image build fails:

```
Paketo Buildpack for CPython 1.13.0

  Resolving CPython version

    Candidate version sources (in priority order):

                -> ""

      <unknown> -> ""

Selected CPython version (using ): 3.10.14

 Executing build process

    Installing CPython 3.10.14

failed to fetch dependency: failed to make request: Get https://artifacts.paketo.io/python/python_3.10.14_linux_x64_jammy_9e7c333f.tgz: dial tcp: lookup
```

How can we redirect artifacts.paketo.io to local server.  Or are there other options for air gapped image creation?

**Comment by chenbh** [comment]
It is up to the individual buildpack authors to decide how to fetch their dependencies. There appears to be an open issue at https://github.com/paketo-buildpacks/cpython/issues/819 about being able to use dependency mirroring
