### ISSUE TITLE
Support signing for images resulting from Builders/ClusterBuilders

### ISSUE THREAD

**Issue by stormqueen1990** [buildpacks-community/kpack#942]
The [cosign integration RFC](https://github.com/pivotal/kpack/blob/main/rfcs/0007-cosign-integration.md) specifies generation of signatures for images generated by kpack's `Image`, `Build`, `Builder`, and `ClusterBuilder` resources. However, kpack does not currently sign images resulting from `Builder` and `ClusterBuilder` resources.

**Comment by ThomasVitale** [comment]
This would be a great addition to kpack. I can see that there's a draft pull request addressing this issue. What is the status?
